{% set name = "opticalglass" %}
{% set version = "1.1.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d2ec0d06e7e16dd4a76a34f1678abb7b8dfba195bb5e6c6ffb3ef1c046a85b0

build:
  number: 0
  noarch: python
  entry_points:
    - glassmap = opticalglass.glassmapviewer:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pyscaffold >=4.3
    - setuptools >=46.1.0
    - setuptools-scm
    - python >=3.8
  run:
    - python >={{ python_min }}
    - numpy >=2.3.1
    - scipy >=1.16.0
    - matplotlib-base >=3.10.3
    - pandas >=2.3.0
    - xlrd >=2.0.1
    - openpyxl >=3.1.5
    - requests >=2.32.4
    - json_tricks >=3.17.3
    - pyyaml >=6.0.2
    - pyside6 >=6.9.1

test:
  imports:
    - opticalglass
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/opticalglass/
  summary: Tools for reading commercial optical glass catalogs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    opticalglass is a Python package to interface with optical glass
    manufacturers glass data spreadsheets. It provides a neutral API
    to query data from multiple catalogs as well as the RefractiveIndex.Info 
    website. A Matplotlib graphical glass map display can be used 
    from scripts and the Qt-based glassmap app is built on top of 
    this capability.
  doc_url: https://opticalglass.readthedocs.io/
  dev_url: https://github.com/mjhoptics/opticalglass

extra:
  recipe-maintainers:
    - mjhoptics
