{% set name = "opticalglass" %}
{% set version = "1.2.0" %}
{% set python_min = "3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bee2328232e30c602dac68b093c6b304c698f788673378c1afcefb44de5c4c8f

build:
  number: 0
  noarch: python
  entry_points:
    - glassmap = opticalglass.glassmapviewer:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pyscaffold >=4.3
    - setuptools >=46.1.0
    - setuptools-scm
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy >=2.4.3
    - scipy >=1.17.1
    - matplotlib-base >=3.10.8
    - pandas >=3.0.2
    - xlrd >=2.0.2
    - openpyxl >=3.1.5
    - requests >=2.33.1
    - json_tricks >=3.17.3
    - pyyaml >=6.0.3
    - pyside6 >=6.11.0

test:
  imports:
    - opticalglass
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/opticalglass/
  summary: Tools for reading commercial optical glass catalogs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    opticalglass is a Python package to interface with optical glass
    manufacturers glass data spreadsheets. It provides a neutral API
    to query data from multiple catalogs as well as the RefractiveIndex.Info 
    website. A Matplotlib graphical glass map display can be used 
    from scripts and the Qt-based glassmap app is built on top of 
    this capability.
  doc_url: https://opticalglass.readthedocs.io/
  dev_url: https://github.com/mjhoptics/opticalglass

extra:
  recipe-maintainers:
    - mjhoptics
