{% set name = "opticalglass" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4494b97f5dfd6c55e3c7eebf29ee29cb346ee3b8d6a8c028338f9aa151568d4d

build:
  number: 1
  noarch: python
  entry_points:
    - glassmap = opticalglass.glassmapviewer:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - numpy >=1.21.5
    - scipy >=1.7.3
    - matplotlib-base >=3.5.1
    - pandas >=1.3.5
    - xlrd >=2.0.1
    - openpyxl >=3.0.9
    - requests >=2.27.1
    - pyyaml >=6.0
    - pyqt <5.16

test:
  imports:
    - opticalglass
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/opticalglass/
  summary: Tools for reading commercial optical glass catalogs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    opticalglass is a Python package to interface with optical glass
    manufacturers glass data spreadsheets. It provides a neutral API
    to query data from multiple catalogs as well as the RefractiveIndex.Info 
    website. A Matplotlib graphical glass map display can be used 
    from scripts and the Qt-based glassmap app is built on top of 
    this capability.
  doc_url: https://opticalglass.readthedocs.io/
  dev_url: https://github.com/mjhoptics/opticalglass

extra:
  recipe-maintainers:
    - mjhoptics
