{% set name = "opticalglass" %}
{% set version = "1.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a59dccf6f04aa3d243c6a662970473a2e6777e31963f6baf1f4993417cd00906

build:
  number: 1
  noarch: python
  entry_points:
    - glassmap = opticalglass.glassmapviewer:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pyscaffold >=4.3
    - setuptools >=46.1.0
    - setuptools-scm
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - numpy >=2.1.3
    - scipy >=1.14.1
    - matplotlib-base >=3.9.2
    - pandas >=2.2.3
    - xlrd >=2.0.1
    - openpyxl >=3.1.2
    - requests >=2.32.3
    - pyyaml >=6.0.1
    - pyside6 >=6.7.3

test:
  imports:
    - opticalglass
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/opticalglass/
  summary: Tools for reading commercial optical glass catalogs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    opticalglass is a Python package to interface with optical glass
    manufacturers glass data spreadsheets. It provides a neutral API
    to query data from multiple catalogs as well as the RefractiveIndex.Info 
    website. A Matplotlib graphical glass map display can be used 
    from scripts and the Qt-based glassmap app is built on top of 
    this capability.
  doc_url: https://opticalglass.readthedocs.io/
  dev_url: https://github.com/mjhoptics/opticalglass

extra:
  recipe-maintainers:
    - mjhoptics
