{% set name = "opticalglass" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7740b127717abe865b7881b35605655b921859b4cf10f815148e8b0ff7e8cf66

build:
  number: 3
  noarch: python
  entry_points:
    - glassmap = opticalglass.glassmapviewer:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - matplotlib-base >=3.1.1
    - numpy >=1.17.1
    - pyqt <5.13
    - python >=3.7
    - scipy >=1.3.1
    - xlrd >=2.0.1
    - openpyxl >=3.0.5

test:
  imports:
    - opticalglass
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/opticalglass/
  summary: Tools for reading commercial optical glass catalogs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    opticalglass is a Python package to interface with optical glass
    manufacturers glass data spreadsheets. It provides a neutral API
    to query data from multiple catalogs. A Matplotlib graphical glass
    map display can be used from scripts and the Qt-based glassmap app
    is built on top of this capability.
  doc_url: https://opticalglass.readthedocs.io/
  dev_url: https://github.com/mjhoptics/opticalglass

extra:
  recipe-maintainers:
    - mjhoptics
